export const SHEETS = {
  GMV: "REPLACE_GMV_LINK",
  MOM: "REPLACE_MOM_LINK",
  DATE_WISE: "REPLACE_DATE_WISE_LINK",
  MONTH_WISE_SKU: "REPLACE_MONTH_WISE_SKU_LINK",
  MONTH_WISE_LOCATION: "REPLACE_MONTH_WISE_LOCATION_LINK",
  MONTH_WISE_FULFILLMENT: "REPLACE_MONTH_WISE_FULFILLMENT_LINK",
  DATE_WISE_VERTICAL: "REPLACE_DATE_WISE_VERTICAL_LINK",
  MONTH_WISE_VERTICAL: "REPLACE_MONTH_WISE_VERTICAL_LINK"
};
